import type { AccountRole } from "@/lib/auth/roles";
import type { InteractiveMessagePayload } from "@/lib/whatsapp/interactive";
import type { IntakeFormConfig } from "@/lib/intake-forms/types";

export type {
  InteractiveMessagePayload,
  InteractiveButtonsPayload,
  InteractiveListPayload,
  InteractiveButton,
  InteractiveListRow,
  InteractiveListSection,
} from "@/lib/whatsapp/interactive";

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  /**
   * User's own preferred sidebar nav order — an array of hrefs, e.g.
   * ["/agenda", "/dashboard", ...]. Null means "use the default
   * order" (see 048_profile_nav_order.sql). A per-person preference,
   * not an account-wide setting.
   */
  nav_order?: string[] | null;
  /** Professional title, e.g. "Dr.", "Dra.", "Lic." */
  title?: string | null;
  specialty?: string | null;
  /** Cédula profesional / matrícula. */
  license_number?: string | null;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  /** URL segment for the public booking page (/agendar/[slug]). Null = not published. */
  public_booking_slug?: string | null;
  public_booking_enabled?: boolean;
  created_at: string;
  updated_at: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, "owner">;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  phone: string;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  name?: string;
  /** Split-name fields (migration 069). `name` stays in sync with
   *  these via a DB trigger whenever they're written — every other
   *  read path (avatars, previews, search) still just reads `name`. */
  first_name?: string | null;
  last_name?: string | null;
  nickname?: string | null;
  email?: string;
  company?: string;
  avatar_url?: string;
  landline_phone?: string | null;
  address?: string | null;
  lead_source?: string | null;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `contact_tags(tags(*))` (e.g. the
   *  Inbox conversation list, for tag filtering). Absent otherwise. */
  tags?: Tag[];
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  field_type: string;
  field_options?: Record<string, unknown>;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

export interface ContactNote {
  id: string;
  contact_id: string;
  user_id: string;
  note_text: string;
  created_at: string;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

export interface Conversation {
  id: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  assigned_agent_id?: string;
  last_message_text?: string;
  last_message_at?: string;
  unread_count: number;
  created_at: string;
  updated_at: string;
  contact?: Contact;
  /**
   * AI auto-reply state for this thread (migration 029 + 033):
   *  - `ai_autoreply_disabled` — the bot is paused here (a human took
   *    over, or the model handed off). Sticky until re-enabled.
   *  - `ai_reply_count` — how many times the bot has auto-replied,
   *    checked against the account's per-conversation cap.
   *  - `ai_handoff_summary` — short internal note the bot wrote when it
   *    handed off, shown to whoever takes the thread over.
   */
  ai_autoreply_disabled?: boolean;
  ai_reply_count?: number;
  ai_handoff_summary?: string | null;
}

// ============================================================
// Notifications (migration 027)
// ============================================================

export type NotificationType = 'conversation_assigned';

export interface Notification {
  id: string;
  account_id: string;
  /** Recipient — the agent this notification is for. */
  user_id: string;
  type: NotificationType;
  conversation_id?: string;
  contact_id?: string;
  /** Who triggered it. Null when an automation/system assigned it. */
  actor_user_id?: string;
  title: string;
  body?: string;
  read_at?: string;
  created_at: string;
}

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive';
export type MessageStatus = 'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /**
   * Structured payload of an OUTBOUND interactive message (reply
   * buttons or list) we sent. Lets the thread re-render the buttons /
   * rows, not just the body text. Only set when `content_type ===
   * 'interactive'` and `sender_type` is agent/bot. Migration 035.
   */
  interactive_payload?: InteractiveMessagePayload;
  /**
   * True when the AI auto-reply bot generated + sent this message (as
   * opposed to a human agent or a deterministic Flow/automation send,
   * which all share `sender_type='bot'`/`'agent'`). Drives the "AI"
   * badge in the inbox. Migration 033.
   */
  ai_generated?: boolean;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  phone_number_id: string;
  waba_id?: string;
  access_token: string;
  verify_token?: string;
  status: 'connected' | 'disconnected';
  connected_at?: string;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. */
  last_registration_error?: string;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
}

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  header_type?: 'text' | 'image' | 'video' | 'document';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  sample_values?: TemplateSampleValues;
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  created_at: string;
}

/** Fixed set of appointment/contact fields a reminder template's
 *  `{{N}}` placeholder can be bound to — resolved server-side in the
 *  reminders cron, never trusted from the client beyond this enum. */
export type ReminderVariableToken =
  | 'contact_name'
  | 'appointment_date'
  | 'appointment_time'
  | 'doctor_name'
  | 'service_name'
  | 'account_name';

export type ReminderVariableMapping =
  | { type: 'static'; value: string }
  | { type: 'token'; value: ReminderVariableToken };

export interface AppointmentReminderConfig {
  id: string;
  account_id: string;
  is_active: boolean;
  hours_before: number;
  template_name: string | null;
  template_language: string | null;
  variable_mapping: Record<string, ReminderVariableMapping>;
  created_at: string;
  updated_at: string;
}

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
}

export interface PipelineStage {
  id: string;
  pipeline_id: string;
  name: string;
  position: number;
  color: string;
  created_at: string;
}

export type DealStatus = 'open' | 'won' | 'lost';

export interface Deal {
  id: string;
  user_id: string;
  pipeline_id: string;
  stage_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved.
   */
  contact_id: string | null;
  conversation_id?: string;
  assigned_to?: string;
  title: string;
  value: number;
  currency?: string;
  notes?: string;
  expected_close_date?: string;
  status?: DealStatus;
  created_at: string;
  updated_at?: string;
  contact?: Contact;
  stage?: PipelineStage;
  assignee?: Profile;
}

// ------------------------------------------------------------
// Clinic scheduling (rooms, doctors, appointments) — see
// supabase/migrations/037_clinic_scheduling_core.sql.
// ------------------------------------------------------------

export interface Doctor {
  id: string;
  account_id: string;
  /** Nullable — a doctor doesn't need a Zentro Med login to be assignable. */
  user_id: string | null;
  name: string;
  specialty?: string | null;
  is_active: boolean;
  google_calendar_connected: boolean;
  google_calendar_id?: string | null;
  google_calendar_connected_at?: string | null;
  /** Formulario de admisión de pacientes (premium) — null = sin configurar. */
  intake_form_config?: IntakeFormConfig | null;
  created_at: string;
  updated_at?: string;
}

export interface Room {
  id: string;
  account_id: string;
  name: string;
  /** Surfaced as the Google Calendar event's location when an appointment in this room syncs. */
  address?: string | null;
  is_active: boolean;
  created_at: string;
  updated_at?: string;
}

export interface ServiceType {
  id: string;
  account_id: string;
  name: string;
  duration_minutes: number;
  is_active: boolean;
  /** Billing catalog price this service type is priced from, if linked. */
  product_id?: string | null;
  created_at: string;
  updated_at?: string;
  product?: Product;
}

export interface DoctorAvailabilityBlock {
  id: string;
  account_id: string;
  doctor_id: string;
  start_at: string;
  end_at: string;
  notes?: string | null;
  created_at: string;
  updated_at?: string;
}

export type AppointmentStatus = 'pending' | 'confirmed' | 'completed' | 'cancelled' | 'no_show';
export type AppointmentSource = 'cal_com' | 'manual' | 'public_booking';

export interface Appointment {
  id: string;
  account_id: string;
  deal_id: string | null;
  contact_id: string | null;
  doctor_id: string | null;
  room_id: string | null;
  service_type_id: string | null;
  start_at: string;
  end_at: string;
  status: AppointmentStatus;
  source: AppointmentSource;
  cal_com_booking_uid?: string | null;
  google_calendar_event_id?: string | null;
  notes?: string | null;
  created_by?: string | null;
  created_at: string;
  updated_at?: string;
  doctor?: Doctor;
  room?: Room;
  service_type?: ServiceType;
  contact?: Contact;
}

// ------------------------------------------------------------
// Clinical records (EHR) — see
// supabase/migrations/038_clinical_records.sql. `clinical_notes` and
// `clinical_note_addenda` are immutable once written (enforced by a
// DB trigger, not just app logic) — there is no update/edit shape for
// either type on purpose.
// ------------------------------------------------------------

export interface PatientProfile {
  id: string;
  account_id: string;
  contact_id: string;
  assigned_doctor_id: string | null;
  blood_type?: string | null;
  allergies?: string | null;
  chronic_conditions?: string | null;
  current_medications?: string | null;
  emergency_contact_name?: string | null;
  emergency_contact_phone?: string | null;
  notes?: string | null;
  document_type?: string | null;
  document_number?: string | null;
  birth_date?: string | null;
  birth_country?: string | null;
  hc_number?: string | null;
  insurance_provider?: string | null;
  business_line?: string | null;
  patient_group?: string | null;
  occupation?: string | null;
  sex?: string | null;
  created_by?: string | null;
  created_at: string;
  updated_at?: string;
  assigned_doctor?: Doctor;
}

export interface ClinicalNoteAddendum {
  id: string;
  account_id: string;
  clinical_note_id: string;
  content: string;
  created_by?: string | null;
  created_at: string;
}

export interface ClinicalNote {
  id: string;
  account_id: string;
  patient_profile_id: string;
  doctor_id: string | null;
  appointment_id: string | null;
  chief_complaint: string;
  findings_and_plan: string;
  /** Generated column — SHA-256 of chief_complaint + findings_and_plan
   *  (migration 073), snapshotted at patient-signing time. */
  content_hash?: string;
  signed_at: string;
  created_by?: string | null;
  created_at: string;
  doctor?: Doctor;
  addenda?: ClinicalNoteAddendum[];
}

// ============================================================
// Odontogram (migration 066) — current per-tooth status for a
// converted patient (keyed off patient_profile_id, same as
// clinical_notes). FDI/ISO two-digit tooth numbering (11-18, 21-28,
// 31-38, 41-48 — permanent adult dentition only in this version).
// ============================================================

export type ToothCondition =
  | 'healthy'
  | 'caries'
  | 'filled'
  | 'crown'
  | 'root_canal'
  | 'missing'
  | 'extraction_planned'
  | 'implant'
  | 'bridge';

export interface OdontogramTooth {
  id: string;
  account_id: string;
  patient_profile_id: string;
  tooth_number: number;
  condition: ToothCondition;
  notes?: string | null;
  /** Free-text ICD-10/ICD-11 diagnostic code (migration 071). */
  icd_code?: string | null;
  updated_by?: string | null;
  created_at: string;
  updated_at: string;
}

// ============================================================
// Visit photos (migration 067) — durable clinical photo history per
// patient, optionally tied to the appointment/visit it was taken
// during. Stored in the private `clinical-photos` bucket, served via
// short-lived signed URLs (never a public bucket — this is patient
// medical imagery).
// ============================================================

export interface VisitPhoto {
  id: string;
  account_id: string;
  patient_profile_id: string;
  appointment_id?: string | null;
  storage_path: string;
  caption?: string | null;
  /** Original filename — stored explicitly (migration 070) since
   *  non-image files have no thumbnail to fall back on for display. */
  file_name?: string | null;
  content_type?: string | null;
  uploaded_by?: string | null;
  created_at: string;
}

// ============================================================
// Informed consent + e-signature (migration 072). `content_hash` is
// a Postgres GENERATED column (SHA-256 of `content`) so it can never
// drift from what's actually stored — that's what proves the text
// wasn't altered after the patient signed it.
// ============================================================

export type ConsentDocumentStatus = 'pending' | 'signed' | 'declined' | 'expired';
export type ConsentDocumentSourceType = 'text' | 'pdf';

export type StampFieldType = 'signature' | 'signer_name' | 'signed_date' | 'custom_text';

/** One independently-positioned element stamped onto a PDF at signing
 *  time (migration 075) — `x`/`y` are page-relative fractions with a
 *  bottom-left origin, matching pdf-lib's coordinate system directly.
 *  `id` disambiguates same-type fields — only 'custom_text' ever has
 *  more than one instance; the other three types are capped at one
 *  each by the picker UI. `label`/`value` only apply to 'custom_text':
 *  `label` is the prompt staff set once on the template (e.g.
 *  "Procedimiento"); `value` is filled in per-patient when a document
 *  is created from that template (see consent-forms-tab.tsx), then
 *  stamped as-is at signing time — the other three types compute
 *  their stamped text from the signer's name/the signing date instead. */
export interface StampField {
  id: string;
  type: StampFieldType;
  label?: string;
  value?: string;
  page: number;
  x: number;
  y: number;
}

/** A reusable PDF consent template (migration 074/075) — the legal
 *  text is fixed; only where the signature/name/date get stamped is
 *  configured, once, and reused for every patient sent this template. */
export interface ConsentTemplate {
  id: string;
  account_id: string;
  name: string;
  storage_path: string;
  stamp_fields: StampField[];
  created_by?: string | null;
  created_at: string;
}

export interface ConsentDocument {
  id: string;
  account_id: string;
  patient_profile_id: string;
  title: string;
  source_type: ConsentDocumentSourceType;
  /** Set when source_type === 'text'. */
  content?: string | null;
  content_hash?: string | null;
  /** Set when source_type === 'pdf'. */
  template_id?: string | null;
  pdf_storage_path?: string | null;
  pdf_hash?: string | null;
  stamp_fields?: StampField[] | null;
  status: ConsentDocumentStatus;
  /** Migration 077 — optional link to the appointment this consent belongs to. */
  appointment_id?: string | null;
  created_by?: string | null;
  created_at: string;
  updated_at: string;
}

/** Read-only from the client — every row is written by the
 *  submit_signature() RPC, never a direct insert. `signed_pdf_storage_path`
 *  is only set for PDF-sourced documents — the final stamped artifact. */
export interface ConsentSignature {
  id: string;
  account_id: string;
  consent_document_id: string;
  signer_name: string;
  signer_email: string;
  signature_storage_path: string;
  signed_pdf_storage_path?: string | null;
  otp_verified_at: string;
  document_hash_at_signing: string;
  ip_address?: string | null;
  user_agent?: string | null;
  signed_at: string;
}

/** The emailed link + OTP mechanism. `otp_code_hash`/`otp_attempts`/
 *  `otp_verified_at`/`redeemed_at` are only ever written by the
 *  request_signature_otp/verify_signature_otp/submit_signature RPCs.
 *  Points at exactly one signable target — consent_document_id XOR
 *  clinical_note_id (migration 073's num_nonnulls check). */
export interface SignatureRequest {
  id: string;
  account_id: string;
  consent_document_id?: string | null;
  clinical_note_id?: string | null;
  token_hash: string;
  delivered_to_email: string;
  otp_expires_at?: string | null;
  otp_attempts: number;
  otp_verified_at?: string | null;
  redeemed_at?: string | null;
  expires_at: string;
  created_by?: string | null;
  created_at: string;
}

/** Read-only from the client — every row is written by
 *  submit_signature() (migration 073), never a direct insert. */
export interface ClinicalNoteSignature {
  id: string;
  account_id: string;
  clinical_note_id: string;
  signer_name: string;
  signer_email: string;
  signature_storage_path: string;
  otp_verified_at: string;
  document_hash_at_signing: string;
  ip_address?: string | null;
  user_agent?: string | null;
  signed_at: string;
}

export type BroadcastStatus = 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
export type RecipientStatus = 'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed';

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  template_name: string;
  template_language: string;
  template_variables?: Record<string, unknown>;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  created_at: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  error_message?: string;
  /**
   * Meta's message id, persisted when the broadcast send succeeds so
   * the webhook can mirror status updates back onto the recipient row.
   * Added in migration 003.
   */
  whatsapp_message_id?: string;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'time_based'
  /** Customer tapped a reply button / list row whose id matches; lets
   *  multi-step menus be chained across automations. */
  | 'interactive_reply';

export type AutomationStepType =
  | 'send_message'
  | 'send_buttons'
  | 'send_list'
  | 'send_template'
  | 'add_tag'
  | 'remove_tag'
  | 'assign_conversation'
  | 'update_contact_field'
  | 'create_deal'
  | 'wait'
  | 'condition'
  | 'send_webhook'
  | 'send_conversion_event'
  | 'close_conversation';

export type AutomationLogStatus = 'success' | 'partial' | 'failed';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  match_type: 'exact' | 'contains';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export interface InteractiveReplyTriggerConfig {
  /** Button / list-row ids to match, exact. Any one matching fires. */
  reply_ids: string[];
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | InteractiveReplyTriggerConfig
  | Record<string, unknown>;

export interface SendMessageStepConfig {
  text: string;
}

/**
 * `send_buttons` / `send_list` step configs carry the full interactive
 * payload (same shape stored on messages + quick replies). `kind` is
 * implied by the step_type but kept on the payload for a uniform shape.
 */
export type SendButtonsStepConfig = InteractiveMessagePayload;
export type SendListStepConfig = InteractiveMessagePayload;

export interface SendTemplateStepConfig {
  template_name: string;
  language?: string;
  variables?: Record<string, string>;
}

export interface TagStepConfig {
  tag_id: string;
}

export interface AssignConversationStepConfig {
  mode: 'specific' | 'round_robin';
  agent_id?: string;
}

export interface UpdateContactFieldStepConfig {
  /**
   * Either a built-in contact column (`name` | `email` | `company`) or a
   * custom field encoded as `custom:<custom_field_id>`. The `custom:` prefix
   * is how the engine distinguishes a `contact_custom_values` write from a
   * direct `contacts` column update. Older configs store the bare column name,
   * so this stays backward compatible.
   */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  pipeline_id: string;
  stage_id: string;
  title: string;
  value?: number;
}

export interface WaitStepConfig {
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
}

export type ConditionSubject =
  | 'contact_field'
  | 'tag_presence'
  | 'message_content'
  | 'time_of_day';

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /** e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on subject */
  operand?: string;
  /** For contact_field equals / message_content contains — comparison value */
  value?: string;
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

/**
 * Meta-only — Google Ads has no server-side path without OAuth (see
 * src/lib/conversions/), so this step can't fire a gtag conversion;
 * it sends a Meta CAPI event using the account's Settings → Conversions
 * token. `meta_event_name` is free text (Meta's standard vocabulary
 * like "Lead" / "Purchase", or a custom event name).
 */
export interface SendConversionEventStepConfig {
  meta_event_name: string;
  value?: number;
  currency?: string;
}

export type AutomationStepConfig =
  | SendMessageStepConfig
  | SendButtonsStepConfig
  | SendListStepConfig
  | SendTemplateStepConfig
  | TagStepConfig
  | AssignConversationStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | SendConversionEventStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: 'yes' | 'no' | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: 'success' | 'skipped' | 'failed';
  detail?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  error_message?: string | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Quick replies — reusable snippets (migration 035)
// ============================================================

export type QuickReplyKind = 'text' | 'interactive';

export interface QuickReply {
  id: string;
  /** Account tenancy key — shared across all members of the account. */
  account_id: string;
  /** Author / audit only. */
  user_id: string;
  title: string;
  kind: QuickReplyKind;
  /** Set when `kind === 'text'`. */
  content_text?: string | null;
  /** Set when `kind === 'interactive'`. */
  interactive_payload?: InteractiveMessagePayload | null;
  created_at: string;
  updated_at: string;
}

// ------------------------------------------------------------
// Billing — quotes, catalog, taxes, invoices, payments (see
// supabase/migrations/039_billing_core.sql).
// ------------------------------------------------------------

export interface Product {
  id: string;
  account_id: string;
  name: string;
  description?: string | null;
  unit_price: number;
  is_active: boolean;
  created_at: string;
  updated_at?: string;
}

export interface Tax {
  id: string;
  account_id: string;
  name: string;
  /** Percentage, e.g. 16 for 16%. */
  rate: number;
  is_default: boolean;
  is_active: boolean;
  created_at: string;
  updated_at?: string;
}

export type QuoteStatus = 'draft' | 'sent' | 'accepted' | 'rejected' | 'expired' | 'converted';
export type DiscountType = 'percent' | 'fixed' | null;

/** Migración 106 — agrupa líneas de un plan de tratamiento ("Fase 1:
 *  Urgencias", etc). Tabla hija de `quotes`, misma forma de RLS que
 *  `quote_items` (su propia `account_id`, no heredada). */
export interface QuotePhase {
  id: string;
  account_id: string;
  quote_id: string;
  name: string;
  position: number;
  created_at: string;
}

export interface QuoteItem {
  id: string;
  account_id: string;
  quote_id: string;
  product_id: string | null;
  description: string;
  quantity: number;
  unit_price: number;
  tax_id: string | null;
  tax_rate_snapshot: number;
  discount_type: DiscountType;
  discount_value: number;
  line_total: number;
  position: number;
  created_at: string;
  /** Migración 105 — de qué hallazgo del odontograma vino esta línea, si aplica. */
  odontogram_tooth_id?: string | null;
  odontogram_tooth?: { tooth_number: number } | null;
  /** Migración 106. */
  phase_id?: string | null;
  /** Migración 106 — marcado por el médico cuando el tratamiento de esa línea ya se realizó. */
  completed: boolean;
  product?: Product;
  tax?: Tax;
  phase?: QuotePhase;
}

export interface Quote {
  id: string;
  account_id: string;
  contact_id: string;
  deal_id: string | null;
  /** Migration 077 — optional link to the appointment this quote belongs to. */
  appointment_id?: string | null;
  quote_number: string;
  status: QuoteStatus;
  issue_date: string;
  expiry_date?: string | null;
  subtotal: number;
  tax_total: number;
  discount_type: DiscountType;
  discount_value: number;
  discount_amount: number;
  total: number;
  currency: string;
  notes?: string | null;
  created_by?: string | null;
  created_at: string;
  updated_at?: string;
  /** Migración 106 — cuándo pasó a `status: 'accepted'` (distinto de
   *  `issue_date`/`updated_at`, que cambian con cualquier edición). */
  approved_at?: string | null;
  contact?: Contact;
  items?: QuoteItem[];
  phases?: QuotePhase[];
}

export type InvoiceStatus = 'draft' | 'sent' | 'paid' | 'partial' | 'overdue' | 'void';

export interface InvoiceItem {
  id: string;
  account_id: string;
  invoice_id: string;
  product_id: string | null;
  description: string;
  quantity: number;
  unit_price: number;
  tax_id: string | null;
  tax_rate_snapshot: number;
  discount_type: DiscountType;
  discount_value: number;
  line_total: number;
  position: number;
  created_at: string;
  product?: Product;
  tax?: Tax;
}

export interface Invoice {
  id: string;
  account_id: string;
  contact_id: string;
  deal_id: string | null;
  quote_id: string | null;
  /** Migration 077 — optional link to the appointment this invoice belongs to. */
  appointment_id?: string | null;
  invoice_number: string;
  status: InvoiceStatus;
  issue_date: string;
  due_date?: string | null;
  subtotal: number;
  tax_total: number;
  discount_type: DiscountType;
  discount_value: number;
  discount_amount: number;
  total: number;
  /** Maintained by a DB trigger off `payments` — never set directly. */
  amount_paid: number;
  currency: string;
  notes?: string | null;
  created_by?: string | null;
  created_at: string;
  updated_at?: string;
  contact?: Contact;
  items?: InvoiceItem[];
  payments?: Payment[];
}

export type PaymentMethod = 'cash' | 'card' | 'transfer' | 'other';

export interface Payment {
  id: string;
  account_id: string;
  invoice_id: string;
  amount: number;
  method: PaymentMethod;
  paid_at: string;
  notes?: string | null;
  /** Migration 079 — optional link to which bank account received this payment. */
  bank_account_id?: string | null;
  created_by?: string | null;
  created_at: string;
}

// ============================================================
// Finance module, phase 1 (migration 078) — expenses, so a basic
// profit/loss report (payments collected minus expenses) is possible
// ahead of the later bank-accounts/cash-flow and inventory phases.
// ============================================================

export type ExpenseCategory =
  | 'rent'
  | 'payroll'
  | 'supplies'
  | 'utilities'
  | 'marketing'
  | 'equipment'
  | 'taxes'
  | 'software'
  | 'other';

export interface Expense {
  id: string;
  account_id: string;
  category: ExpenseCategory;
  description: string;
  amount: number;
  currency: string;
  expense_date: string;
  vendor?: string | null;
  payment_method: PaymentMethod;
  /** Migration 079 — optional link to which bank account this was paid from. */
  bank_account_id?: string | null;
  notes?: string | null;
  created_by?: string | null;
  created_at: string;
  updated_at?: string;
}

// ============================================================
// Finance module, phase 2 (migration 079) — bank accounts + cash
// flow. `computed_balance` is never stored — it's opening_balance
// plus attributed payments/expenses/bank_transactions, summed in JS
// the same way Phase 1's P&L summed invoices/expenses (see
// financial-summary.tsx) — only present when the API route computed
// it (the list endpoint does; a bare insert response won't).
// ============================================================

export interface BankAccount {
  id: string;
  account_id: string;
  name: string;
  bank_name?: string | null;
  account_number_last4?: string | null;
  currency: string;
  opening_balance: number;
  is_active: boolean;
  computed_balance?: number;
  created_by?: string | null;
  created_at: string;
  updated_at?: string;
}

export type BankTransactionDirection = 'in' | 'out';
export type BankTransactionCategory =
  | 'transfer'
  | 'owner_draw'
  | 'capital_contribution'
  | 'bank_fee'
  | 'interest'
  | 'other';

export interface BankTransaction {
  id: string;
  account_id: string;
  bank_account_id: string;
  direction: BankTransactionDirection;
  category: BankTransactionCategory;
  amount: number;
  description: string;
  transaction_date: string;
  created_by?: string | null;
  created_at: string;
}

// ============================================================
// Finance module, phase 3 (migration 080) — inventory of supplies,
// materials, and instruments. `computed_stock` is never stored —
// same "opening balance + movements" shape as BankAccount's
// computed_balance, summed server-side by the list route.
// ============================================================

export type InventoryCategory = 'supplies' | 'materials' | 'instruments' | 'equipment' | 'other';

export interface InventoryItem {
  id: string;
  account_id: string;
  name: string;
  category: InventoryCategory;
  sku?: string | null;
  unit: string;
  unit_cost?: number | null;
  initial_stock: number;
  minimum_stock: number;
  supplier?: string | null;
  is_active: boolean;
  computed_stock?: number;
  created_by?: string | null;
  created_at: string;
  updated_at?: string;
}

export type InventoryMovementDirection = 'in' | 'out';
export type InventoryMovementReason = 'purchase' | 'consumption' | 'waste' | 'adjustment' | 'other';

export interface InventoryMovement {
  id: string;
  account_id: string;
  item_id: string;
  direction: InventoryMovementDirection;
  reason: InventoryMovementReason;
  quantity: number;
  unit_cost_at_time?: number | null;
  expense_id?: string | null;
  notes?: string | null;
  movement_date: string;
  created_by?: string | null;
  created_at: string;
}

/** Platform-admin-controlled promo/announcement shown in the dashboard carousel. */
export interface PlatformAnnouncement {
  id: string;
  title: string;
  body: string;
  image_url?: string | null;
  link_url?: string | null;
  link_label?: string | null;
  is_active: boolean;
  starts_at?: string | null;
  ends_at?: string | null;
  sort_order: number;
  created_by?: string | null;
  created_at: string;
  updated_at?: string;
}
