import { createHmac, timingSafeEqual } from "node:crypto";

/**
 * Stateless signed unsubscribe token — encodes contactId+accountId
 * directly rather than a random opaque token stored in a table (like
 * signature_requests), since an unsubscribe link has no one-time-use
 * or expiry semantics to enforce; just "prove this was generated by
 * us for this contact." Format: `${contactId}.${accountId}.${hmacHex}`.
 */

function getSecret(): string {
  const secret = process.env.EMAIL_UNSUBSCRIBE_SECRET;
  if (!secret) throw new Error("EMAIL_UNSUBSCRIBE_SECRET is not configured");
  return secret;
}

function sign(contactId: string, accountId: string): string {
  return createHmac("sha256", getSecret()).update(`${contactId}:${accountId}`).digest("hex");
}

export function buildUnsubscribeToken(contactId: string, accountId: string): string {
  return `${contactId}.${accountId}.${sign(contactId, accountId)}`;
}

export function buildUnsubscribeUrl(contactId: string, accountId: string, baseUrl: string): string {
  const token = buildUnsubscribeToken(contactId, accountId);
  return `${baseUrl.replace(/\/+$/, "")}/api/email/unsubscribe?token=${encodeURIComponent(token)}`;
}

export function verifyUnsubscribeToken(token: string): { contactId: string; accountId: string } | null {
  const parts = token.split(".");
  if (parts.length !== 3) return null;
  const [contactId, accountId, signature] = parts;
  const expected = sign(contactId, accountId);
  const a = Buffer.from(signature);
  const b = Buffer.from(expected);
  if (a.length !== b.length || !timingSafeEqual(a, b)) return null;
  return { contactId, accountId };
}
